apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-1709
  labels:
    app: whoami-1709
spec:
  replicas: 1
  template:
    metadata:
      name: whoami-1709
      labels:
        app: whoami-1709
      annotations:
        experimental.windows.kubernetes.io/isolation-type: hyperv
    spec:
      containers:
      - name: whoami-1709
        image: stefanscherer/whoami:windows-amd64-1.5.4-1709
        ports:
        - containerPort: 8080
      nodeSelector:
        beta.kubernetes.io/os: windows
  selector:
    matchLabels:
      app: whoami-1709
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-1709-svc
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: whoami-1709

