apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-2016
  labels:
    app: whoami-2016
spec:
  replicas: 1
  template:
    metadata:
      name: whoami-2016
      labels:
        app: whoami-2016
      annotations:
        experimental.windows.kubernetes.io/isolation-type: hyperv
    spec:
      containers:
      - name: whoami-2016
        image: stefanscherer/whoami:windows-amd64-1.7.0
        ports:
        - containerPort: 8080
      nodeSelector:
        beta.kubernetes.io/os: windows
  selector:
    matchLabels:
      app: whoami-2016
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-2016-svc
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: whoami-2016

